In [16]:
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(x.eval())
writer.close()

5


In [5]:
x = tf.Variable(tf.random_normal([1]))

In [6]:
sess = tf.Session()

In [8]:
sess.run(tf.global_variables_initializer())

In [11]:
sess.run(x)

array([-1.5875229], dtype=float32)

In [12]:
sess.run(x)

array([-1.5875229], dtype=float32)

In [13]:
sess.run(x.initializer)

In [14]:
sess.run(x)

array([-0.2609244], dtype=float32)

In [15]:
print(x.eval())

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`